USE banking_analysis

UPDATE CUSTOMERS
SET 
	CUSTOMER_NAME = UPPER(CUSTOMER_NAME),
	GENDER = UPPER(GENDER),
	CITY = UPPER(CITY);

SELECT * 
FROM CUSTOMERS
WHERE CUSTOMER_NAME IS NULL OR CITY IS NULL;

SELECT 
	CUSTOMER_NAME,
	COUNT(*) AS DUPLICATE_COUNT
FROM CUSTOMERS
GROUP BY CUSTOMER_NAME
HAVING COUNT(*)>1;

UPDATE CUSTOMERS
SET CUSTOMER_NAME = TRIM(CUSTOMER_NAME);

SELECT *
FROM ACCOUNTS
WHERE BALANCE < 0;

SELECT * 
FROM TRANSCATIONS
WHERE TRANSACTION_STATUS = 'FAILED' OR ATM_ID IS NULL;

SELECT * 
FROM TRANSCATIONS
WHERE AMOUNT > 10000;

SELECT * 
FROM LOANS
WHERE LOAN_AMOUNT <= 0;

SELECT * 
FROM ATMS
WHERE ATM_STATUS = 'INACTIVE';

EXEC sp_rename 'TRANSCATIONS', 'TRANSACTIONS';

SELECT * FROM TRANSACTIONS
