USE banking_analysis;

SELECT
SUM(AMOUNT) AS TOTAL_TRANSACTION_AMOUNT
FROM TRANSCATIONS;

SELECT
	TRANSACTION_TYPE,
	COUNT(*) AS TOTAL_TRANSACTIONS,
	SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSCATIONS
GROUP BY TRANSACTION_TYPE;

SELECT 
	TRANSACTION_STATUS,
	COUNT(*) AS TOTAL_FAILED_TRANSACTIONS
FROM TRANSCATIONS
WHERE TRANSACTION_STATUS = 'FAILED'
GROUP BY TRANSACTION_STATUS;

SELECT  TOP 5
TRANSACTION_ID,
ACCOUNT_ID,
AMOUNT
FROM TRANSCATIONS
ORDER BY AMOUNT DESC;

SELECT
ROUND((SUM(CASE 
              WHEN TRANSACTION_STATUS = 'FAILED'
			  THEN 1
			  ELSE 0
			END) * 100.0)/COUNT(*),
2) AS FAILED_TRANSACTION_PERCENTAGE
FROM TRANSACTIONS;
             


