USE banking_analysis

SELECT 
	REPAYMENT_STATUS,
	COUNT(*) AS TOTAL_LOANS,
	SUM(LOAN_AMOUNT) AS TOTAL_LOAN_AMOUNT
FROM LOANS
GROUP BY REPAYMENT_STATUS;

SELECT
	c.CUSTOMER_NAME,
	l.LOAN_TYPE,
	l.LOAN_AMOUNT
FROM CUSTOMERS c
JOIN LOANS l
ON c.CUSTOMER_ID = l.CUSTOMER_ID
ORDER BY l.LOAN_AMOUNT DESC;

SELECT
	c.CUSTOMER_NAME,
	l.LOAN_TYPE,
	l.REPAYMENT_STATUS
FROM CUSTOMERS c
JOIN LOANS l
ON c.CUSTOMER_ID = l.CUSTOMER_ID
WHERE REPAYMENT_STATUS = 'LATE'

SELECT
AVG(LOAN_AMOUNT) AS AVERAGE_LOAN_AMOUNT
FROM LOANS;
