USE banking_analysis

SELECT
	a.ATM_ID,
	a.ATM_LOCATION,
	COUNT(t.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
	SUM(t.AMOUNT) AS TOTAL_CASH_USED
FROM ATMS a
JOIN TRANSACTIONS t
ON a.ATM_ID = t.ATM_ID
GROUP BY
	a.ATM_ID,
	a.ATM_LOCATION
ORDER BY TOTAL_TRANSACTIONS DESC;

SELECT
	ATM_ID,
	COUNT(*) AS FAILED_TRANSACTIONS
FROM TRANSACTIONS
WHERE TRANSACTION_STATUS = 'FAILED'
AND ATM_ID IS NOT NULL
GROUP BY ATM_ID;

SELECT 
	ATM_STATUS,
	COUNT(*) AS TOTAL_ATMS
FROM ATMS
GROUP BY ATM_STATUS;


