CREATE DATABASE banking_analysis;
USE banking_analysis;

--create tables
--===============CUSTOMER TABLE================
CREATE TABLE CUSTOMERS(
	CUSTOMER_ID INT PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(100),
	AGE INT,
	GENDER VARCHAR(20),
	CITY VARCHAR(50),
	CUSTOMER_SINCE DATE
);
--===============ACCOUNTS TABLE================
CREATE TABLE ACCOUNTS(
	ACCOUNT_ID INT PRIMARY KEY,
	CUSTOMER_ID INT,
	ACCOUNT_TYPE VARCHAR(50),
	BALANCE DECIMAL(12,2),
	ACCOUNT_OPEN_DATE DATE,
	FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

--==============TRANSACTIONS TABLE==============
CREATE TABLE TRANSCATIONS(
	TRANSACTION_ID INT PRIMARY KEY,
	ACCOUNT_ID INT,
	TRANSACTION_DATE DATETIME,
	TRANSACTION_TYPE VARCHAR(20),
	AMOUNT DECIMAL(12,2),
	CHANNEL VARCHAR(30),
	MERCHANT_CATEGORY VARCHAR(50),
	TRANSACTION_STATUS VARCHAR(20),
	ATM_ID INT,
	FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)
);

--==============LOANS TABLE==================
CREATE TABLE LOANS(
	LOAN_ID INT PRIMARY KEY,
	CUSTOMER_ID INT,
	LOAN_TYPE VARCHAR(50),
	LOAN_AMOUNT DECIMAL(12,2),
	INTEREST_RATE DECIMAL(5,2),
	DUE_DATE DATE,
	REPAYMENT_STATUS VARCHAR(30),
	FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

--=============ATMs TABLE=================
CREATE TABLE ATMS(
	ATM_ID INT PRIMARY KEY,
	ATM_LOCATION VARCHAR(100),
	CITY VARCHAR(50),
	ATM_STATUS VARCHAR(20)
);






