USE banking_analysis;

SELECT
	TRANSACTION_ID,
	ACCOUNT_ID,
	AMOUNT,
	TRANSACTION_DATE
FROM TRANSACTIONS
WHERE AMOUNT> 1000;

SELECT
TRANSACTION_ID,
ACCOUNT_ID,
TRANSACTION_DATE,
AMOUNT
FROM TRANSACTIONS
WHERE DATEPART(HOUR, TRANSACTION_DATE) BETWEEN 0 AND 5;

SELECT 
ACCOUNT_ID,
COUNT(*) AS FAILED_TRANSACTION_COUNT
FROM TRANSACTIONS
WHERE TRANSACTION_STATUS = 'FAILED'
GROUP BY ACCOUNT_ID;



