USE banking_analysis;

SELECT
	TRANSACTION_ID,
	ACCOUNT_ID,
	AMOUNT,
	TRANSACTION_DATE
FROM TRANSACTIONS
WHERE AMOUNT> 1000;

SELECT
	TRANSACTION_ID,
	ACCOUNT_ID,
	TRANSACTION_DATE,
	AMOUNT
FROM TRANSACTIONS
WHERE DATEPART(HOUR, TRANSACTION_DATE) BETWEEN 0 AND 5;

SELECT 
	ACCOUNT_ID,
	COUNT(*) AS FAILED_TRANSACTION_COUNT
FROM TRANSACTIONS
WHERE TRANSACTION_STATUS = 'FAILED'
GROUP BY ACCOUNT_ID;

SELECT
	t.TRANSACTION_ID,
	a.CUSTOMER_ID,
	t.AMOUNT,
	t.TRANSACTION_DATE
FROM TRANSACTIONS t
JOIN ACCOUNTS a
ON  t.ACCOUNT_ID = a.ACCOUNT_ID
WHERE AMOUNT > 10000
ORDER BY AMOUNT DESC




