USE banking_analysis

SELECT
	c.CUSTOMER_ID,
	c.CUSTOMER_NAME,
	c.CITY,
	a.BALANCE,
	CASE
	   WHEN a.BALANCE >= 50000 THEN 'HIGH VALUE'
	   WHEN a.BALANCE >= 10000 THEN 'MEDIUM VALUE'
	   ELSE 'LOW VALUE'
	END AS CUSTOMER_SEGMENT
FROM CUSTOMERS c
JOIN ACCOUNTS a
ON c.CUSTOMER_ID = a.CUSTOMER_ID;

SELECT TOP 5
	c.CUSTOMER_NAME,
	a.BALANCE
FROM CUSTOMERS c
JOIN ACCOUNTS a
ON c.CUSTOMER_ID = a.CUSTOMER_ID
ORDER BY a.BALANCE DESC;

SELECT
	ACCOUNT_TYPE,
	AVG(BALANCE) AS AVERAGE_BALANCE
FROM ACCOUNTS
GROUP BY ACCOUNT_TYPE;

SELECT
	CITY,
	COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMERS
GROUP BY CITY
ORDER BY TOTAL_CUSTOMERS DESC;

SELECT
	CUSTOMER_NAME,
	AGE,
	CASE WHEN AGE<30 THEN 'YOUNG'
	WHEN AGE BETWEEN 30 AND 50 THEN 'MIDDLE AGE'
	ELSE 'SENIOR'
END AGE_GROUP
FROM CUSTOMERS;


